<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\ProductCategory;
use App\Models\Tenant;
use App\Models\TenantCategory;
use Illuminate\Database\Seeder;

class TenantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get the Banjarmasin branch (code: BJM) as all tenants are for branch_id = 1
        $branch = Branch::where('code', 'BJM')->first();

        if (!$branch) {
            $this->command->error('Branch BJM not found. Please run BranchSeeder first.');
            return;
        }

        // List of tenants with their product category and tenant category
        $tenants = [
            ["name" => "Erha Ultimate", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "ZAP", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "Ekle's Clinic", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "Salsa Musik", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Andari", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Turkish Carpet", "product_category" => "Home & Living", "tenant_category" => "Tenant"],
            ["name" => "De'Gaz", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Doux", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Real Time", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Excel Comp", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Top Seluler", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Grand Arloji", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Golden Boy", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "My John Barbershop", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "Gyavalan Reflexi", "product_category" => "Service", "tenant_category" => "Tenant"],
            ["name" => "Urarchive", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Urarchive", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Pict n Share", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Urarchive", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Violet Collection", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Aibo", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "YL Studio", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Cerita Cinta Studio", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Crown", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Our Studio", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Pegadaian", "product_category" => "Service", "tenant_category" => "Tenant"],
            ["name" => "Focus", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Hoky Cell", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "My Delisha", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Timeless", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Ar Raudhah", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Bless Shoes Store", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Emmy Collection", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Inbox Photo Zone", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Melda Collection", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Jingga", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Ethica", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Gemar", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Azka Collection", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Central Arloji", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "New Silver", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Surya  Mas", "product_category" => "Retail", "tenant_category" => "Tenant"], // Note: empty product category? We'll skip or handle.
            ["name" => "Sahabat Ponsel", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Plaza Optik", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Golden", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Forbes", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "G-Star", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "El Zatta", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Hanaya", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Camela Scarves", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Toko Sepatu Gracia", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Macro Digital ", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Life Time", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Westime", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Al Wafa", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Little Taipei", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "JOLI", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Roti Boy", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Mixue", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Fun City", "product_category" => "Entertainment", "tenant_category" => "Tenant"],
            ["name" => "Toko Emas Hamsa", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Mel''s Collection", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Kidzlander", "product_category" => "Entertainment", "tenant_category" => "Mini Anchor"],
            ["name" => "Pandora", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Kerastase", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "YSL", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "Chang Tea", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Ice Cream Hokky", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Caterpillar (CAT)", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Watch Club", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Willie''s Ice Cream", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Cup & Cup", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Shukago", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Tuk-Tuk Cha", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Yo Crepes", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Yuk The", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Honey Pok", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Yummy Coin", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Pocoyo", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Hey Fries", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Janji Jiwa", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Waffelicious", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Chikuro", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Cup & Cup", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "XXI Café", "product_category" => "F&B", "tenant_category" => "Anchor"],
            ["name" => "Mochigo", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Milop Cheese", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Fun World (Driver Junior)", "product_category" => "Entertainment", "tenant_category" => "Tenant"],
            ["name" => "Chikumi", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Popalicious", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Covistry", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "KFC", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "The Body Shop", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Beard Papa''s", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Roti''O", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Pizza Hut", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Guardian", "product_category" => "Health", "tenant_category" => "Tenant"],
            ["name" => "Dunkin Donuts", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "The Palace", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Excelso", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Ta Wan", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Ichiban Sushi", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "XO Suki", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "XO Cuisine", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Dwidaya Tour", "product_category" => "Service", "tenant_category" => "Tenant"],
            ["name" => "Hypermart", "product_category" => "Department Store", "tenant_category" => "Mini Anchor"], // Note: product category empty? User left blank.
            ["name" => "Zoom Watch", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "KOI Café", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Breadlife", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Willie''s Bakery", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "A&W", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "ATM Center", "product_category" => "Service", "tenant_category" => "Tenant"],
            ["name" => "Fore Coffee", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Boost", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Bicco", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Watsons", "product_category" => "Health", "tenant_category" => "Tenant"],
            ["name" => "Erafone", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Gadget Mart", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "La Casa Gelato", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "D''Master Bakery", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Gadget Mart", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Teazzi", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Xiaomi", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Doran Gadget", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Samsung", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "iBox", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "By Aura", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Donini", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Fitflop", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Beauty Haul", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "Frank & Co", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Sociolla", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "My Feet", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Havaianas", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Staccato", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Urban & Co", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Urban Republic", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "EVB", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Pedro", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Obermain", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Gino Mariani", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Charles & Keith", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Sushi OK!", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Chatime ", "product_category" => "F&B", "tenant_category" => "Tenant"], // Note: trailing space
            ["name" => "Starbucks", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Croco by MS", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Kopi Kenangan", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "HokBen", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Richeese Factory", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Sushi Tei", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Asics", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "New Balance", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "Boncafe", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Foot Locker", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "Aldo", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Garmin", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "HRTA Store", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "JD Sport", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "Bli Bli", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Under Armour", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "Steve Madden", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Lacoste", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Bose", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Nobby", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "3 Second", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "White Mode", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Elizabeth", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Hush Puppies", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Solaria", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Cabe Merah", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Rempah Bistro", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Bellagio", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Batik Keris", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Giordano", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "POLO", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "This is April", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Hammer", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Wrangler", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Lascada", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Levi''s", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Gramedia", "product_category" => "Lifestyle", "tenant_category" => "Mini Anchor"],
            ["name" => "Shafira", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "MDS", "product_category" => "Department Store", "tenant_category" => "Tenant"], // Note: empty product category
            ["name" => "Watchout ", "product_category" => "Retail", "tenant_category" => "Tenant"], // trailing space
            ["name" => "Everbest", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "C&F Parfumery", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Skechers", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "VANS", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Crocs", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Converse", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Puma", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Fisik", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "Triset", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Geulis", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Wacoal", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Saturdays", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Watch Club", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Optik Seis", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Optik Tunggal", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Optik Melawai", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Carthago", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "MOC", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Dust", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Spilla Jewelry", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Colorbox", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Executive", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Magnolia", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Digiplus", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "The Bra House", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Hardware", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Adidas", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "Uniqlo", "product_category" => "Retail", "tenant_category" => "Anchor"],
            ["name" => "New Era", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Kordinat", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Shem Ramen", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "BLTS", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Royal K-BBQ", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Sport Station", "product_category" => "Sport", "tenant_category" => "Tenant"],
            ["name" => "Payless", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Ray Surf", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Celcius", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Mississippi", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Manzone", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Skechers Kids", "product_category" => "Kids", "tenant_category" => "Tenant"],
            ["name" => "Buccheri", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Kids Station", "product_category" => "Kids", "tenant_category" => "Tenant"],
            ["name" => "Playtopia", "product_category" => "Kids", "tenant_category" => "Mini Anchor"],
            ["name" => "Amazone", "product_category" => "Entertainment", "tenant_category" => "Mini Anchor"],
            ["name" => "Montato", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "OWL", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Gosh", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Celcius Woman", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "LOGO", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Donna Prive", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "X-Eight", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Miniso", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Stroberi", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "MDS", "product_category" => "Department Store", "tenant_category" => "Tenant"], // duplicate
            ["name" => "Azko", "product_category" => "Home & Living", "tenant_category" => "Anchor"],
            ["name" => "Toys Kingdom", "product_category" => "Kids", "tenant_category" => "Anchor"],
            ["name" => "Absolute", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "He Tea", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Dr Specs", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Naughty", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Play Works", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Lolypoly", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Fipper", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Kimukatsu", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Yoshinoya", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Shihlin", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Marugame Udon", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Imperial Kitchen & Dimsum", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Pepper Lunch", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Nada Puspita", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Deenay", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "La Sabelle", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Muda", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Vivi Zubedi", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Ayu By Ayu Lestari", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Your Bag Spa", "product_category" => "Service", "tenant_category" => "Tenant"],
            ["name" => "Zytadelia", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Queensland", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Benang Jarum", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Ria Miranda", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Diario", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Ranti", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Klamby", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Button Scarves", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Cindy", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Cols Froyo", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Padhi Tani", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Ramen 1", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Little X-Eight", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Lee Cooper & Cool Kids", "product_category" => "Kids", "tenant_category" => "Tenant"],
            ["name" => "Kidzooona", "product_category" => "Kids", "tenant_category" => "Mini Anchor"],
            ["name" => "Selfie Time", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Ivan Gunawan Prive", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Mothercare & ELC", "product_category" => "Kids", "tenant_category" => "Tenant"],
            ["name" => "Saranghae", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "OH! SOME", "product_category" => "Lifestyle", "tenant_category" => "Mini Anchor"],
            ["name" => "MDLY", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "FuniFun!", "product_category" => "Entertainment", "tenant_category" => "Tenant"],
            ["name" => "Fashion District", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "Hikmat", "product_category" => "Retail", "tenant_category" => "Tenant"],
            ["name" => "ATM Center", "product_category" => "Service", "tenant_category" => "Tenant"], // duplicate
            ["name" => "Photomatics", "product_category" => "Lifestyle", "tenant_category" => "Tenant"],
            ["name" => "Pokemon Mezastar", "product_category" => "Entertainment", "tenant_category" => "Tenant"],
            ["name" => "Cinema XXI", "product_category" => "Entertainment", "tenant_category" => "Tenant"],
            ["name" => "Informa", "product_category" => "Home & Living", "tenant_category" => "Anchor"],
            ["name" => "Johnny Andrean", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "BILLBOSS", "product_category" => "Entertainment", "tenant_category" => "Tenant"],
            ["name" => "Yopie Salon", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "Me Nail", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "Sun.FM", "product_category" => "Entertainment", "tenant_category" => "Tenant"],
            ["name" => "The Barber Suite", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "My Salon", "product_category" => "Beauty", "tenant_category" => "Tenant"],
            ["name" => "Rona Nona", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Crustopia", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Mr. DIY", "product_category" => "Home & Living", "tenant_category" => "Mini Anchor"],
            ["name" => "Es Kopi Indonesia", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Chubby", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Domo Domo", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Es Teh Indonesia", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Timezone", "product_category" => "Entertainment", "tenant_category" => "Mini Anchor"],
            ["name" => "Ria Ayam Penyet", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Electronic City", "product_category" => "Electronics", "tenant_category" => "Tenant"],
            ["name" => "Hi Sushi", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Sancha", "product_category" => "F&B", "tenant_category" => "Tenant"],
            ["name" => "Matahari", "product_category" => "Retail", "tenant_category" => "Anchor"],
        ];

        foreach ($tenants as $tenantData) {
            // Skip if product category is empty (as in some entries)
            if (empty($tenantData['product_category'])) {
                $this->command->info("Skipping tenant '{$tenantData['name']}' due to missing product category.");
                continue;
            }

            $productCategory = ProductCategory::where('name', $tenantData['product_category'])->first();
            $tenantCategory = TenantCategory::where('name', $tenantData['tenant_category'])->first();

            if (!$productCategory) {
                $this->command->error("Product category '{$tenantData['product_category']}' not found for tenant '{$tenantData['name']}'.");
                continue;
            }

            if (!$tenantCategory) {
                $this->command->error("Tenant category '{$tenantData['tenant_category']}' not found for tenant '{$tenantData['name']}'.");
                continue;
            }

            Tenant::firstOrCreate(
                ['name' => $tenantData['name']],
                [
                    'branch_id' => $branch->id,
                    'product_category_id' => $productCategory->id,
                    'tenant_category_id' => $tenantCategory->id,
                ]
            );
        }
    }
}